Context menu
mozilla/glam pull request #1222
Opened 2021-03-01 22:48 UTC by robhudson

2021-03-02 21:18 UTC, wlach requested changes
This looks pretty reasonable in outline-- is there any way for me to test this? See my question in #glam-dev.

2021-03-02 21:18 UTC, wlach commented on src/components/ContextMenu.svelte
> +  // however.
Could you use a component binding? https://svelte.dev/tutorial/component-bindings

2021-03-02 21:18 UTC, wlach commented on src/components/explore/AggregationsOverTimeGraph.svelte
> +    return toQueryString({ ...params, ...paramsToUpdate });
```suggestion
    return activeProductConfig ? toQueryString({ ...activeProductConfig.getParamsForQueryString($store), ...paramsToUpdate }) : '';
```

2021-03-02 21:18 UTC, wlach commented on src/components/explore/ProbeExplorer.svelte
> +    if (str === 'ZOOM') {
I would personally use constants for these things. e.g. `GLAM_ZOOM_KEY` or whatever

2021-03-02 21:18 UTC, wlach commented on src/components/explore/ProbeExplorer.svelte
>    function setDomain(str) {
While you're here, could you use a more descriptive variable name?

```suggestion
  function setDomain(domain) {
```

2021-03-03 19:58 UTC, wlach commented
Some additional feedback after trying this out:

* The right-click behaviour is not really discoverable. Some kind of brief text like *right click on hover to zoom* just below the graph would really help.
* It would be nice if the hovering over behaviour with the graph was disabled while the prompt (zoom from here to the ref point) is enabled
* It wasn't immediately clear to me how to reset the zoom when zoomed in. possibly you could do that by adding a "custom" setting to time horizon when zooming in, and animating the addition of that to the time horizon box: 
![image](https://user-images.githubusercontent.com/20569/109864392-c4628f00-7c30-11eb-855d-50daa655c9a5.png)

Other than that it seems to work as expected!

2021-03-04 19:02 UTC, wlach commented
> It wasn't immediately clear to me how to reset the zoom when zoomed in. possibly you could do that by adding a "custom" setting to time horizon when zooming in, and animating the addition of that to the time horizon box:

So to be clear in that case, the time horizon box would then look like this with the custom option (which would always be selected if present):

![image](https://user-images.githubusercontent.com/20569/110015635-16b7b480-7cf2-11eb-9d43-43bd1b42ed83.png)

In my mind, clicking on any of the other options would hide the custom zoom option.

2021-03-04 19:04 UTC, wlach commented
BTW, I used a similar concept for mission control and I think it works pretty well: https://missioncontrol.telemetry.mozilla.org/#/release/mac/main_crashes

![image](https://user-images.githubusercontent.com/20569/110015969-7f069600-7cf2-11eb-8f16-3b1dff79cc52.png)

I believe GUD also does something like this.

2021-03-08 20:55 UTC, merged

2021-03-08 20:56 UTC, robhudson commented
Merged some fixes to get on dev for further testing. Incremental improvements will be added in other commits.