Show 99 and 99.9 percentiles in table view
mozilla/glam pull request #1649
Opened 2021-10-13 13:52 UTC by Iinh

Now that we added 99 and 99.9 to the list of available percentiles, let's also show them in the table view.

2021-10-13 14:23 UTC, wlach requested changes
Have some minor suggestions here.

2021-10-13 14:23 UTC, wlach commented on src/components/table/TableView.svelte
> +    : visibleBuckets;
IMO it's not ideal to redefine input into a component.

I'm feeling like it makes more sense to do this in the higher level, containing component which already has a fair amount of business logic and keep this one simpler: https://github.com/mozilla/glam/blob/main/src/components/table/ProbeTableView.svelte#L69

There's already a definition of percentiles there. Might make sense to move `METRICS_WITH_PERCENTILE_DATA` to `src/constants.js` while you're at it.

2021-10-14 15:32 UTC, Iinh commented on src/components/table/TableView.svelte
> +    : visibleBuckets;
Thanks @wlach! This is now addressed with the latest commit.

2021-10-14 15:38 UTC, wlach commented on src/components/table/ProbeTableView.svelte
> +    visibleBuckets={probeType === 'categorical' ? visibleBuckets : PERCENTILES}
This doesn't seem *quite* equivalent to your previous commit -- does non-categorical imply `METRICS_WITH_PERCENTILE_DATA`? https://github.com/mozilla/glam/pull/1649/commits/72ef1b9d8ab36241646f039599dafb545c7112d0

2021-10-14 16:25 UTC, Iinh commented on src/components/table/ProbeTableView.svelte
> +    visibleBuckets={probeType === 'categorical' ? visibleBuckets : PERCENTILES}
good catch! let me dig deeper to see if non-categorical is actually equivalent to `METRICS_WITH_PERCENTILE_DATA` 🤔

2021-10-14 18:36 UTC, Iinh commented on src/components/table/ProbeTableView.svelte
> +    visibleBuckets={probeType === 'categorical' ? visibleBuckets : PERCENTILES}
So I was hesitant to use `probeType 'categorical'` as a condition to check whether a metric has percentile data in #1599 because I thought probeType was from viewType, and as defined here:

https://github.com/mozilla/glam/blob/a6b2802ebb3d70ec9372efecd466eb1e298625de/src/routing/wrappers/Probe.svelte#L33

https://github.com/mozilla/glam/blob/a6b2802ebb3d70ec9372efecd466eb1e298625de/src/config/fenix.js#L113-L116

Initially I thought using `viewType` from the above code snippet can't determine whether a metric has percentile or not (my fault!) Upon further checking I realized that there are actually 2 viewType values: one in `$store`, and one in `$dataset` (which is actually the value passed to probeType):

https://github.com/mozilla/glam/blob/a6b2802ebb3d70ec9372efecd466eb1e298625de/src/config/fenix.js#L135

This is a long explanation to answer that yes, non-categorical does imply `METRICS_WITH_PERCENTILE_DATA` (well, actually non-categorical covers more metric types than `METRICS_WITH_PERCENTILE_DATA`, which is good bc it should cover all the percentile metrics that I missed in the last PR 🤦🏻‍♀️)

2021-10-14 18:41 UTC, Iinh commented on src/components/table/TableView.svelte
> +  {#if bucketTypeLabel === 'percentiles'}
My bad, I didn't realize that we already defined `bucketTypeLabel` to handle the use case of differentiating whether a metric has categorical or percentile data.

https://github.com/mozilla/glam/blob/a6b2802ebb3d70ec9372efecd466eb1e298625de/src/components/table/ProbeTableView.svelte#L84-L86

2021-10-15 17:40 UTC, wlach approved these changes
🎉

2021-10-15 19:46 UTC, merged