(fixes #203) add mozilla wordmark to footer
mozilla/glam pull request #220
Opened 2020-01-24 18:26 UTC by spasovski

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/391260/73093747-ca6e3400-3ea4-11ea-9c5b-1415a7baa7c8.png">

2020-01-25 00:20 UTC, hamilton requested changes
lgtm, one minor nit about props, once you take a look feel free to merge at your convenience

2020-01-25 00:20 UTC, hamilton commented on src/components/icons/MozillaLogo.svelte
> +export let size = {width: 100, height: 36};
I'd remove `height` from this and only allow the user to specify width, if possible, to prevent warp

2020-01-29 10:56 UTC, spasovski commented
ready for re-r when you get a chance

2020-01-30 07:54 UTC, hamilton approved these changes
looks good @spasovski – thanks!

2020-01-30 07:54 UTC, merged