(fixes #201) ellipsis long category text overflow
mozilla/glam pull request #250
Opened 2020-02-27 00:00 UTC by spasovski

<img width="375" alt="image" src="https://user-images.githubusercontent.com/391260/75399416-cbd6b600-58c1-11ea-98ba-b3a77458a635.png">

2020-03-04 17:04 UTC, hamilton requested changes
Looking good @spasovski – noticed one minor bug. Once that's fixed, feel free to merge

2020-03-04 17:04 UTC, hamilton commented on src/components/explore/ComparisonSummary.svelte
> +              <td class="value-label" title={keyFormatter(key)}>
wondering if it'd be good to add `use:tooltip` on these TDs:

```
<script>
import { tooltip } from 'udgl/utils/tooltip';
...
</script>

... 
<td class="value-label" use:tooltip={{text: keyFormatter(key), location: 'top'}}>
```

2020-03-04 17:04 UTC, hamilton commented on src/components/explore/ComparisonSummary.svelte
> +              <td class="value-label" use:tooltipAction={{text: keyFormatter(key), location: 'top'}}>
if I hover over the other graph, it appears the tooltip disappears

2020-03-06 21:42 UTC, spasovski commented
Will reopen a new PR for this.

2020-03-06 21:42 UTC, closed without merging