tweaks to summary table
mozilla/glam pull request #353
Opened 2020-03-24 23:39 UTC by hamilton

Closes #345

 - use `transformedPercentiles` for Fx probes in the summary table instead of `percentiles`
- use two-pt decimal percentages in tables where appropriate

2020-03-26 21:55 UTC, openjck commented on src/components/explore/ComparisonSummary.svelte
> -let pFmt = format('.0%');
After this is removed, we get:

`  2:10  error  'format' is defined but never used                               no-unused-vars`

2020-03-26 22:03 UTC, openjck requested changes
Looks good to me aside from that!

2020-03-27 00:55 UTC, openjck commented on src/components/explore/ComparisonSummary.svelte
>  import { format } from 'd3-format';
```suggestion
```

2020-03-27 00:59 UTC, merged

2020-03-27 01:01 UTC, hamilton commented
Thanks for the spot check @openjck ~