adds feedback button to top bar
mozilla/glam pull request #464
Opened 2020-05-04 20:51 UTC by hamilton

closes #454

2020-05-05 17:07 UTC, openjck requested changes

2020-05-05 17:07 UTC, openjck commented on src/routing/wrappers/Layout.svelte
> +        <SlackLogo size={16} />FEEDBACK
Since the capitalization of the word *feedback* is for stylistic purposes only, rather than e.g. to represent an abbreviation, I'd recommend wrapping the word in a `<span>` and styling it with `text-transform: uppercase`.

2020-05-05 17:07 UTC, openjck commented on src/routing/wrappers/Layout.svelte
> +  padding-bottom: var(--space-1h);
These could be combined like:

`padding: var(--space-1h) var(--space-base);`

2020-05-05 17:08 UTC, openjck commented
Otherwise this is really nice! I'm excited to see this improvement land.

2020-05-07 01:01 UTC, hamilton commented
Thanks for the feedback @openjck. Incorporated + will merge

2020-05-07 01:01 UTC, merged