basic search functionality from probe search service
mozilla/glam pull request #594
Opened 2020-06-09 16:28 UTC by spasovski

This continues from hamilton's draft PR. Does not include updated styling considerations.

2020-06-09 23:02 UTC, hamilton requested changes
Thanks for filing @spasovski. I left some comments inline to get you started. They boil down to:

(1) let's filter out events from the postgrest query
(2) fix the `ilike` statement
(3) move the search API stuff into `api.js` as we discussed
(4) the probe type labels should be right-aligned and not identical width necessarily – is that a change from what's on dev?
(5) we need a little spinner at the top right of the search results header when we're awaiting a query to finish running. This can easily be done with a boolean that turns on / off while waiting for a search query
(6) if no results are present, we should say that instead of the "getting the probes – one second!" text
(7) the 400 error should probably be something in the search results body, not a yellow note to the right of everything

2020-06-09 23:02 UTC, hamilton commented on src/components/search/Search.svelte
> +const domain = (str, product = 'desktop') => {
just to note what we discussed over zoom: 

1. let's move this + the `probeSearchService` function over to `api.js`
2. let's decompose the `domain` function into its constituent parts so it is easier to reason about it

2020-06-09 23:02 UTC, hamilton commented on src/components/search/Search.svelte
> +  return `https://dev.probe-search.nonprod.dataops.mozgcp.net/probes?limit=15&select=name,definition,type&product=eq.${product}&or=(name.eq.${formattedStr},index.phfts(english).${formattedStr},descri
more follow-up from chatting:

(1) the `ilike` is technically not doing anything. Moving it to `name.ilike.*${formattedStr}*` will fix it
(2) adding `&type=neq.event` after the `product-eq` statement will filter out events, which I think we need here (we should not be returning events)

2020-06-09 23:02 UTC, hamilton commented on src/components/search/Search.svelte
> +      <div
I think I would expect the error message _in_ the search results area, not off to the side specifically. I would also expect it to be probably not yellow but kind of more in-line with our other error message.

2020-06-09 23:02 UTC, hamilton commented on src/components/search/SearchResults.svelte
>            {:else}
as this is now, I get a `getting the probes – one second!` when there are no search results. If not `results.length`, then we should be saying "no search results found for "____"`

2020-06-09 23:02 UTC, hamilton commented on src/components/search/SearchResults.svelte
> +              <div>getting the probes – one second!</div>
I'm noticing that when I am waiting for the search service to return something, I'm actually not seeing any kind of spinner or anything in the title bar. We know when we're awaiting results – we could just set a flag somewhere in thsi file that is like `isCurrentlyFetching` and pop up the spinner on the right side of the search results header when that is true.

2020-06-09 23:02 UTC, hamilton commented on src/components/search/SearchResults.svelte
>                    <div class="probe-type label label-text--01 label--{type}">{type}</div>
This seems a bit off. The label sizing for scalar is the same as it is for histogram, so the padding looks a little strange. I would expect the label to be right-aligned and not all the same width.

![Screen Shot 2020-06-09 at 1 54 24 PM](https://user-images.githubusercontent.com/95735/84209041-f52ee280-aa69-11ea-8e4f-11b07d0acacc.png)

2020-06-10 18:26 UTC, robhudson commented on src/components/search/Search.svelte
> +  return `https://dev.probe-search.nonprod.dataops.mozgcp.net/probes?limit=15&select=name,definition,type&product=eq.${product}&or=(name.eq.${formattedStr},index.phfts(english).${formattedStr},descri
I would suggest making the base URL for the probe-search service to be configurable in some way. At some point we may have multiple instances for dev & prod.

2020-06-10 21:02 UTC, openjck commented
Superseded by #602

2020-06-10 21:02 UTC, closed without merging